# The Module Name is used as prefix for all contained resources.
Module: LambdaSharp.Challenge.TrainingJob

# The Module Version is shown in the CloudFormation stack and Lambda function descriptions.
Version: 1.0-Dev

# The Module Description is shown in the AWS CloudFormation console with the version number.
Description: Creates a SageMaker BlazinText training job


Using:
    - Module: LambdaSharp.S3.IO:0.5
    
# The Items section defines values and resources for the module.
Items:

# =============================================================================
# S3 Bucket definitions 
# 1) Define S3 Bucket
# 2) Create a public variable, this value will be exported in CF
# 3) Use the S3.IO module to empty the bucket when the stack is removed
# =============================================================================
  - Resource: S3MLData
    Scope: public
    Type: AWS::S3::Bucket
    Allow: ReadWrite

  - Variable: S3MLDataUrl
    Scope: public
    Value: !Sub "s3://${S3MLData}"

  - Resource: EmptyS3MLData
    Type: LambdaSharp::S3::EmptyBucket
    Properties:
      Bucket: !GetAtt S3MLData.Arn
    
# =============================================================================
# Define required permissions to allow lambda function to create a SageMaker
# training job
# 1) Allow the creation of training jobs in SageMaker
# 2) Requires IAM pass role
# https://docs.aws.amazon.com/sagemaker/latest/dg/api-permissions-reference.html
# =============================================================================
  - Resource: SageMakerPermissions
    Scope: all
    Value: "*"
    Allow:
      - "sagemaker:*"
  - Resource: IAMPassRole
    Scope: all
    Value: "*"
    Allow:
      - iam:PassRole 

# =============================================================================
# LambdaSharp custom resource definition. 
# 1) The handler is a reference to the resource that triggers the lambda 
#    function. Currently SNS is the only method supported
# 2) Properties definitions include some basic information to create 
#    the training job
# 3) Attributes are outputs that define the resource such as name 
#    and data localtion
# =============================================================================
  - ResourceType: LambdaSharpChallenge::BlazingTextTrainingJob
    Description: Triggers a training job using BlazingText. The output is the location to the generated files
    Handler: BlazingTextCustomResource
    Properties:

      - Name: S3TrainData
        Description: S3 uri of the training data location 
        Type: String
        Required: true
      - Name: S3ValiadtionData
        Description: S3 uri of the testing/validataion data location
        Type: String
        Required: true
      - Name: S3Output
        Description: S3 uri with the path to where the output file will be saved
        Type: String
        Required: true
      - Name: ExecutionRoleArn
        Description: Arn of the role that will be used for training
        Type: String
        Required: true
      
    Attributes:
      - Name: DataOutput
        Description: The output generated by the training job
        Type: String
      - Name: JobName
        Description: The name of the training job
        Type: String

# =============================================================================
# Lambda event and function definition
# 1) SNS topic that triggers the lambda function
# 2) Lambda function. The time out can be less, but just to be sure 
#    is set to 10 minutes
# =============================================================================
  - Resource: BlazingTextCustomResource
    Type: AWS::SNS::Topic
  - Function: BlazingTextTrainingJobResource
    Description: This function is invoked by CloudFormation
    Memory: 128
    Timeout: 600
    Sources:
      - Topic: !Ref BlazingTextCustomResource
    
